compile:
	gcc teste1_NaoOt.c -lm -o teste1_NaoOt.out
	gcc teste1_Ot.c -lm -o teste1_Ot.out
	gcc teste1_NaoOt.c -O -lm -o teste1_NaoOt_o.out
	gcc teste1_Ot.c -O -lm -o teste1_Ot_o.out
	gcc teste1_NaoOt.c -O1 -lm -o teste1_NaoOt_o1.out
	gcc teste1_Ot.c -O1 -lm -o teste1_Ot_o1.out
	gcc teste1_NaoOt.c -O2 -lm -o teste1_NaoOt_o2.out
	gcc teste1_Ot.c -O2 -lm -o teste1_Ot_o2.out
	gcc teste1_NaoOt.c -O3 -lm -o teste1_NaoOt_o3.out
	gcc teste1_Ot.c -O3 -lm -o teste1_Ot_o3.out
	gcc teste1_NaoOt.c -Os -lm -o teste1_NaoOt_os.out
	gcc teste1_Ot.c -Os -lm -o teste1_Ot_os.out
	gcc teste1_NaoOt.c -Og -lm -o teste1_NaoOt_og.out
	gcc teste1_Ot.c -Og -lm -o teste1_Ot_og.out
	gcc teste1_NaoOt.c -Ofast -lm -o teste1_NaoOt_ofast.out
	gcc teste1_Ot.c -Ofast -lm -o teste1_Ot_ofast.out

run:
	./teste1_NaoOt.out
	./teste1_Ot.out
	./teste1_NaoOt_o.out
	./teste1_Ot_o.out
	./teste1_NaoOt_o1.out
	./teste1_Ot_o1.out
	./teste1_NaoOt_o2.out
	./teste1_Ot_o2.out
	./teste1_NaoOt_o3.out
	./teste1_Ot_o3.out
	./teste1_NaoOt_os.out
	./teste1_Ot_os.out
	./teste1_NaoOt_og.out
	./teste1_Ot_og.out
	./teste1_NaoOt_ofast.out
	./teste1_Ot_ofast.out

compileandrun:
	make compile
	make run