compile:
	gcc teste3_NaoOt.c -fopenmp -O3 -o teste3_NaoOt_o3.out -fopt-info
	gcc teste3_Ot.c -fopenmp -O3 -o teste3_Ot_o3.out -fopt-info

run:
	./teste3_NaoOt_o3.out
	./teste3_Ot_o3.out

compileandrun:
	make compile
	make run